using FluentValidation;
using Mediator;
using OneOf;
using YearPlanningApp.Application.Common.Interfaces;
using YearPlanningApp.Domain.Interfaces;

namespace YearPlanningApp.Application.Export;

public record EmailPdfCommand(
    byte[] PdfBytes,
    string FileName,
    string Subject
) : ICommand<OneOf<Success, Error>>, IAuthenticatedCommand;

public class EmailPdfCommandValidator : AbstractValidator<EmailPdfCommand>
{
    public EmailPdfCommandValidator()
    {
        RuleFor(x => x.PdfBytes).NotEmpty().Must(b => b.Length <= 10 * 1024 * 1024)
            .WithMessage("PDF must not exceed 10 MB");
        RuleFor(x => x.FileName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Subject).NotEmpty().MaximumLength(200);
    }
}

public class EmailPdfCommandHandler : ICommandHandler<EmailPdfCommand, OneOf<Success, Error>>
{
    private readonly ICurrentUserService _currentUser;
    private readonly IUnitOfWork _uow;
    private readonly IEmailService _email;

    public EmailPdfCommandHandler(ICurrentUserService currentUser, IUnitOfWork uow, IEmailService email)
    {
        _currentUser = currentUser;
        _uow = uow;
        _email = email;
    }

    public async ValueTask<OneOf<Success, Error>> Handle(EmailPdfCommand command, CancellationToken ct)
    {
        var user = await _uow.Users.GetByIdAsync(_currentUser.UserId, ct);
        if (user is null) return new Error("User not found");

        var htmlBody = $"""
            <div style="font-family:sans-serif;max-width:600px;margin:auto;padding:24px">
              <h2 style="color:#0D6E6E">🌊 Your Flowkigai export is ready</h2>
              <p>Hi {user.DisplayName},</p>
              <p>Please find your <strong>{command.Subject}</strong> attached to this email.</p>
              <p style="color:#6B7280;font-size:13px">Generated by Flowkigai &mdash; your year planning companion.</p>
            </div>
            """;

        await _email.SendWithAttachmentAsync(
            user.Email,
            user.DisplayName,
            $"Flowkigai — {command.Subject}",
            htmlBody,
            command.PdfBytes,
            command.FileName,
            ct);

        return new Success();
    }
}

public record Success;
public record Error(string Message);
