// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YearPlanningApp.Infrastructure.Persistence;

#nullable disable

namespace YearPlanningApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318103923_AddPasswordReset")]
    partial class AddPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.FlowSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_minutes");

                    b.Property<int>("AmbientSound")
                        .HasColumnType("integer")
                        .HasColumnName("ambient_sound");

                    b.Property<string>("Blockers")
                        .HasColumnType("text")
                        .HasColumnName("blockers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int?>("EnergyAfterRating")
                        .HasColumnType("integer")
                        .HasColumnName("energy_after_rating");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<int?>("FlowQualityRating")
                        .HasColumnType("integer")
                        .HasColumnName("flow_quality_rating");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("InterruptionReason")
                        .HasColumnType("text")
                        .HasColumnName("interruption_reason");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("planned_minutes");

                    b.Property<string>("SessionIntention")
                        .HasColumnType("text")
                        .HasColumnName("session_intention");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasInterrupted")
                        .HasColumnType("boolean")
                        .HasColumnName("was_interrupted");

                    b.HasKey("Id")
                        .HasName("pk_flow_sessions");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_flow_sessions_active")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("idx_flow_sessions_user_started");

                    b.ToTable("flow_sessions");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlignedValueNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aligned_value_names");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer")
                        .HasColumnName("goal_type");

                    b.Property<int>("LifeArea")
                        .HasColumnType("integer")
                        .HasColumnName("life_area");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WhyItMatters")
                        .HasColumnType("text")
                        .HasColumnName("why_it_matters");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("UserId", "Year")
                        .HasDatabaseName("idx_goals_user_year")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserId", "Year", "EnergyLevel")
                        .HasDatabaseName("idx_goals_user_year_energy")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CelebrationRitual")
                        .HasColumnType("text")
                        .HasColumnName("celebration_ritual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("IdealDose")
                        .HasColumnType("text")
                        .HasColumnName("ideal_dose");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<string>("MinimumViableDose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minimum_viable_dose");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TrackingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("tracking_method");

                    b.Property<string>("Trigger")
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("GoalId");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<DateTime>("LoggedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_habit_logs");

                    b.HasIndex("HabitId", "LoggedDate")
                        .HasDatabaseName("idx_habit_logs_habit_date");

                    b.ToTable("habit_logs");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.IkigaiJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_ikigai_journeys");

                    b.HasIndex("UserId", "Year")
                        .IsUnique()
                        .HasDatabaseName("idx_ikigai_journey_user_year")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("ikigai_journeys");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.IkigaiRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer")
                        .HasColumnName("room_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ikigai_rooms");

                    b.HasIndex("JourneyId");

                    b.ToTable("ikigai_rooms");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("GoalId");

                    b.ToTable("milestones");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.MindMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_mind_maps");

                    b.HasIndex("UserId", "Year")
                        .IsUnique()
                        .HasDatabaseName("idx_mind_maps_user_year")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("mind_maps");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.MindMapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<int?>("IkigaiCategory")
                        .HasColumnType("integer")
                        .HasColumnName("ikigai_category");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int?>("LifeArea")
                        .HasColumnType("integer")
                        .HasColumnName("life_area");

                    b.Property<Guid?>("LinkedGoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_goal_id");

                    b.Property<Guid>("MindMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("mind_map_id");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer")
                        .HasColumnName("node_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mind_map_nodes");

                    b.HasIndex("MindMapId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("mind_map_nodes");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.NorthStar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_north_stars");

                    b.HasIndex("JourneyId")
                        .IsUnique();

                    b.HasIndex("UserId", "Year")
                        .IsUnique()
                        .HasDatabaseName("idx_north_star_user_year");

                    b.ToTable("north_stars");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GoalDeadlineDaysBeforeList")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal_deadline_days_before_list");

                    b.Property<bool>("GoalDeadlineEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("goal_deadline_enabled");

                    b.Property<bool>("HabitStreakRiskEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("habit_streak_risk_enabled");

                    b.Property<int>("HabitStreakRiskHour")
                        .HasColumnType("integer")
                        .HasColumnName("habit_streak_risk_hour");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WeeklyReviewDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_review_day_of_week");

                    b.Property<bool>("WeeklyReviewEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("weekly_review_enabled");

                    b.Property<int>("WeeklyReviewHour")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_review_hour");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_notification_preferences_user")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("notification_preferences");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .HasDatabaseName("idx_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_push_subscriptions_user");

                    b.ToTable("push_subscriptions");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("EnergyRating")
                        .HasColumnType("integer")
                        .HasColumnName("energy_rating");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<int>("ReviewType")
                        .HasColumnType("integer")
                        .HasColumnName("review_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("UserId", "ReviewType", "PeriodStart")
                        .HasDatabaseName("idx_reviews_user_type_period");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.SmartGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Achievable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achievable");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Measurable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measurable");

                    b.Property<string>("Relevant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relevant");

                    b.Property<string>("Specific")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specific");

                    b.Property<DateTime>("TimeBound")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_bound");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_smart_goals");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.ToTable("smart_goals");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlignedValueNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aligned_value_names");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DependsOnTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_task_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<bool>("IsNextAction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_next_action");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_items");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("idx_task_items_goal_next_action")
                        .HasFilter("is_next_action = true AND status != 3");

                    b.HasIndex("MilestoneId");

                    b.ToTable("task_items");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarProvider")
                        .HasColumnType("text")
                        .HasColumnName("calendar_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token_hash");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.UserValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("IkigaiJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("ikigai_journey_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_name");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_user_values");

                    b.HasIndex("IkigaiJourneyId");

                    b.ToTable("user_values");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.WoopReflection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Obstacle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obstacle");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Wish")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wish");

                    b.HasKey("Id")
                        .HasName("pk_woop_reflections");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.ToTable("woop_reflections");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.FlowSession", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Goal", "Goal")
                        .WithMany("FlowSessions")
                        .HasForeignKey("GoalId")
                        .HasConstraintName("fk_flow_sessions_goals_goal_id");

                    b.HasOne("YearPlanningApp.Domain.Entities.User", null)
                        .WithMany("FlowSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flow_sessions_users_user_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Goal", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Habit", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habits_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.HabitLog", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Habit", "Habit")
                        .WithMany("Logs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_logs_habits_habit_id");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.IkigaiJourney", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.User", "User")
                        .WithMany("IkigaiJourneys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ikigai_journeys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.IkigaiRoom", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.IkigaiJourney", "Journey")
                        .WithMany("Rooms")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ikigai_rooms_ikigai_journeys_journey_id");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Goal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.MindMapNode", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.MindMap", "MindMap")
                        .WithMany("Nodes")
                        .HasForeignKey("MindMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mind_map_nodes_mind_maps_mind_map_id");

                    b.HasOne("YearPlanningApp.Domain.Entities.MindMapNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_mind_map_nodes_mind_map_nodes_parent_node_id");

                    b.Navigation("MindMap");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.NorthStar", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.IkigaiJourney", "Journey")
                        .WithOne("NorthStar")
                        .HasForeignKey("YearPlanningApp.Domain.Entities.NorthStar", "JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_north_stars_ikigai_journeys_journey_id");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.SmartGoal", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Goal", "Goal")
                        .WithOne("SmartGoal")
                        .HasForeignKey("YearPlanningApp.Domain.Entities.SmartGoal", "GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_smart_goals_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Milestone", "Milestone")
                        .WithMany("Tasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_items_milestones_milestone_id");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.UserValue", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.IkigaiJourney", null)
                        .WithMany("Values")
                        .HasForeignKey("IkigaiJourneyId")
                        .HasConstraintName("fk_user_values_ikigai_journeys_ikigai_journey_id");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.WoopReflection", b =>
                {
                    b.HasOne("YearPlanningApp.Domain.Entities.Goal", "Goal")
                        .WithOne("WoopReflection")
                        .HasForeignKey("YearPlanningApp.Domain.Entities.WoopReflection", "GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_woop_reflections_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Goal", b =>
                {
                    b.Navigation("FlowSessions");

                    b.Navigation("Milestones");

                    b.Navigation("SmartGoal");

                    b.Navigation("WoopReflection");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Habit", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.IkigaiJourney", b =>
                {
                    b.Navigation("NorthStar");

                    b.Navigation("Rooms");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.Milestone", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.MindMap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.MindMapNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("YearPlanningApp.Domain.Entities.User", b =>
                {
                    b.Navigation("FlowSessions");

                    b.Navigation("Goals");

                    b.Navigation("IkigaiJourneys");
                });
#pragma warning restore 612, 618
        }
    }
}
