// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using YearPlanningApp.Infrastructure.Persistence;

#nullable disable

namespace YearPlanningApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318062401_AddIkigaiCategoryAndIconToMindMapNode")]
    partial class AddIkigaiCategoryAndIconToMindMapNode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
